### ISSUE TITLE
1.3.1 gets confused with digits and dashes

### ISSUE THREAD

**Issue by m1nde** [nficano/humps#18] opened 2019-08-22 11:18 UTC
Version 1.2.0:
```
>>> humps.camelize("test-1-2-3-4-5-6")
'test123456'
```

Version 1.3.1:
```
>>> humps.camelize("test-1-2-3-4-5-6")
'test12-34-56'
```

**Comment by mm-matthias** [comment] 2019-08-23 09:36
I think this is a duplicate of #16 . As explained in that issue the problem was not resolved with the 1.3.1 release. WDYT @nficano ?

**Comment by jfgreen** [comment] 2020-02-04 14:31
Possibly related:

Version 1.2.0:

```
humps.camelize("foo_1_bar")
'foo1Bar'
```

Version 1.3.1

```
>>> humps.camelize("foo_1_bar")
'foo1_bar'
```

**Comment by zyv** [comment] 2020-11-10 10:07
Unfortunately, this is still broken in 1.6.1:

```python
assert humps.depascalize('error_400') == 'error_400'
assert humps.depascalize('error_a32') == 'error_a32'
```

@nficano

**Closed** 2021-09-23 12:22 UTC
Labels: help wanted
